### ISSUE TITLE
Pressing the play button restarts song from the beginning

### ISSUE THREAD

**Issue by ashe540** [VictorMMorant/djhack#1]
After pausing the current song, pressing the play button restarts the song from the beginning. It should resume playing from the current location.

**Comment by mathieudutour** [comment]
Good to see you're still working on it :)

**Comment by ashe540** [comment]
There were a few things to touch up still. A couple of small things ;)

**Comment by mathieudutour** [comment]
I've created a react component for swiping to reveal option: https://github.com/enki-com/react-swipe-to-reveal-options
I'll translate it to meteor if i have time

**Comment by ashe540** [comment]
Looks great! That would be awesome to integrate for the voting system.
